### ISSUE TITLE
Problems with core.py/python3

### ISSUE THREAD

**Issue by VladMironov** [bmcfee/librosa#183]
I've got small error in ipython while using second example.
Simple 'xrange to range' change fixed it.
```
In [19]:y_h, y_p = librosa.effects.hpss(y)

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-19-c68f0c36b61f> in <module>()
----> 1 y_h, y_p = librosa.effects.hpss(y)

/usr/local/lib/python3.4/site-packages/librosa/effects.py in hpss(y)
     36 
     37     # Compute the STFT matrix
---> 38     D = librosa.core.stft(y)
     39 
     40     # Decompose into harmonic and percussives

/usr/local/lib/python3.4/site-packages/librosa/core.py in stft(y, n_fft, hop_length, win_length, window, center, dtype)
    356                                       * stft_matrix.itemsize))
    357 
--> 358     for bl_s in xrange(0, stft_matrix.shape[1], n_columns):
    359         bl_t = min(bl_s + n_columns, stft_matrix.shape[1])
    360 

NameError: name 'xrange' is not defined
```

**Comment by bmcfee** [comment]
Can you try to reproduce this in 0.4-pre (or the development branch)?  I'm pretty sure this is already fixed.

The 0.3 branch was not entirely py3 compatible, but 0.4 onwards should be.

**Comment by VladMironov** [comment]
Now this:
```
In [3]:y, sr = librosa.load(librosa.util.example_audio_file())

---------------------------------------------------------------------------
NoBackendError                            Traceback (most recent call last)
<ipython-input-3-1c3f0c525dc9> in <module>()
----> 1 y, sr = librosa.load(librosa.util.example_audio_file())

/usr/local/lib/python3.4/site-packages/librosa/core/audio.py in load(path, sr, mono, offset, duration, dtype)
    106 
    107     y = []
--> 108     with audioread.audio_open(os.path.realpath(path)) as input_file:
    109         sr_native = input_file.samplerate
    110 

/usr/local/lib/python3.4/site-packages/audioread/__init__.py in audio_open(path)
     94 
     95     # All backends failed!
---> 96     raise NoBackendError()

NoBackendError: 
```
Obviously my audioread doesn't support .ogg
So I checked the rest of example "Audio effects and playback..." with old .mp3 and version 0.4 -- and it works perfectly!

Also ipython still shows me this warning:
```
/usr/local/lib/python3.4/site-packages/librosa/core/audio.py:34: UserWarning: Could not import scikits.samplerate. Falling back to scipy.signal
  'Falling back to scipy.signal')
```
That's all because I don't have module info from 2009:
```
import scikits.samplerate
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-6200dc87e4a3> in <module>()
----> 1 import scikits.samplerate

/usr/local/lib/python3.4/site-packages/scikits/samplerate/__init__.py in <module>()
      2 # Last Change: Thu Mar 26 01:00 AM 2009 J
      3 
----> 4 from info import __doc__
      5 
      6 from _samplerate import resample, available_convertors, src_version_str, \

ImportError: No module named 'info'
```

**Comment by bmcfee** [comment]
> Obviously my audioread doesn't support .ogg

That sounds easily fixable.

Unless we move the example to wav, I don't think it's generally possible to have an example that works for any audioread install/combination of backends.  For now, I'm going to punt on this, but may revisit in #140 .

> So I checked the rest of example "Audio effects and playback..." with old .mp3 and version 0.4 -- and it works perfectly!

Ok!

> That's all because I don't have module info from 2009:

Sounds like a problem with scikits.samplerate not having a correct `setup.py`.

It looks like all the problems in this thread are either already resolved, or external to librosa, so I'll mark it closed.

**Comment by urinieto** [comment]
I'm also having problems with `samplerate` and Python 3. @VladMironov, how did you end up fixing that? Thanks!

**Comment by VladMironov** [comment]
>how did you end up fixing that?

I used this python3.4 fork: https://github.com/gregorias/samplerate , I hope this would help.

**Comment by urinieto** [comment]
Nice! This fixed it. Thanks a lot!

**Comment by bmcfee** [comment]
I have a mirror of that fork at https://github.com/bmcfee/samplerate , which is what gets installed in the travis-ci build.

**Comment by VladMironov** [comment]
Since I have this error again (now on EC2 Ubuntu) and this post is on Google's top, here's solution for missing mp3 library:
`sudo apt-get install libav-tools`

**Comment by multivac61** [comment]
I have the same error for python 3.5, I tried using the python3.4 samplerate fork but the error is still there. I'm running Ubuntu 15.10 64bit.

**Comment by bmcfee** [comment]
> I have the same error for python 3.5, I tried using the python3.4 samplerate fork but the error is still there.

Which error are you talking about, backend/codec or samplerate?

BTW, the samplerate warning will no longer appear from 0.4.3 onward (since merging #324), as we have a replacement library now for fast resampling.  If you want to try installing the latest dev version directly from github, it may simplify a few things.

**Comment by multivac61** [comment]
I was talking about the samplerate error, glad to see it's been dealt with :+1:

**Comment by Kamatio** [comment]
Hello everyone, May you help me to correct this error..
" ---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-12-50847b43215c> in <module>()
     14 
     15 # Compute MFCC features from the raw signal
---> 16 mfcc = librosa.feature.mfcc(y=y, sr=sr, hop_length= hop_length, n_mfcc=13)
     17 
     18 # And the first-order differences (delta features)

NameError: name 'hop_length' is not defined " 

I am using Anaconda Python 3.5 on Jupyter.....

**Comment by bmcfee** [comment]
@Kamatio Please do not add new questions to closed discussion threads about other topics.

Your problem appears to be due to not setting the value of `hop_length`; try saying `hop_length = 512` before that call.
